tracer:
  serviceName: Frontend
  enabled: true
  dispatchers:
    - type: logger
      loggerName: dispatcher
    - type: remote
      client:
        type: agent
        host: localhost
        format:
          type: protobuf

server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9092

logging:
  level: INFO
